name: Deploy to AWS

on:
  push:
	branches: [main]

jobs:
  deploy:
	runs-on: ubuntu-latest
	steps:
  	- name: Checkout code
    	uses: actions/checkout@v4

  	- name: Login to Docker Hub
    	uses: docker/login-action@v3
    	with:
      	username: ${{ secrets.DOCKERHUB_USERNAME }}
      	password: ${{ secrets.DOCKERHUB_TOKEN }}

  	- name: Build and push Docker image
    	run: |
      	docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/proyecto_fastapi:latest .
      	docker push ${{ secrets.DOCKERHUB_USERNAME }}/proyecto_fastapi:latest

  	- name: Deploy to EC2
    	uses: appleboy/ssh-action@v1.0.3
    	with:
      	host: ${{ secrets.AWS_HOSTNAME }}
      	username: ${{ secrets.AWS_USERNAME }}
      	key: ${{ secrets.AWS_PRIVATEKEY }}
      	script: |
        	docker pull ${{ secrets.DOCKERHUB_USERNAME }}/proyecto_fastapi:latest
        	docker compose -f docker-compose.yml up -d
